osx_image: xcode8.3
language: objective-c
xcode_project: SinceLast.xcodeproj
xcode_scheme: SinceLastTests
before_install: 
  - carthage bootstrap
script:
  - xcodebuild clean build test -sdk iphonesimulator -project SinceLast.xcodeproj -scheme SinceLastTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' CODE_SIGNING_REQUIRED=NO | xcpretty