osx_image: xcode8.3
language: objective-c
xcode_project: SinceLast.xcodeproj
xcode_scheme: SinceLast
before_install: 
  - carthage bootstrap
script:
  - xcodebuild clean build test -sdk iphonesimulator -project SinceLast.xcodeproj -scheme SinceLast CODE_SIGNING_REQUIRED=NO | xcpretty