osx_image: xcode8.3
language: swift
xcode_project: SinceLast.xcodeproj
xcode_scheme: SinceLast
before_install: 
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage bootstrap --verbose